import { cva } from "../../libs";

export const getSpacerClasses = cva("", {
  variants: {
    axis: {
      horizontal: "flex-shrink-0",
      vertical: "flex-shrink-0",
    },
    size: {
      1: "",
      2: "",
      3: "",
      4: "",
      5: "",
      6: "",
      8: "",
      10: "",
      12: "",
      16: "",
      20: "",
      24: "",
    },
  },
  compoundVariants: [
    { axis: "horizontal", size: 1, className: "w-1" },
    { axis: "horizontal", size: 2, className: "w-2" },
    { axis: "horizontal", size: 3, className: "w-3" },
    { axis: "horizontal", size: 4, className: "w-4" },
    { axis: "horizontal", size: 5, className: "w-5" },
    { axis: "horizontal", size: 6, className: "w-6" },
    { axis: "horizontal", size: 8, className: "w-8" },
    { axis: "horizontal", size: 10, className: "w-10" },
    { axis: "horizontal", size: 12, className: "w-12" },
    { axis: "horizontal", size: 16, className: "w-16" },
    { axis: "horizontal", size: 20, className: "w-20" },
    { axis: "horizontal", size: 24, className: "w-24" },
    { axis: "vertical", size: 1, className: "h-1" },
    { axis: "vertical", size: 2, className: "h-2" },
    { axis: "vertical", size: 3, className: "h-3" },
    { axis: "vertical", size: 4, className: "h-4" },
    { axis: "vertical", size: 5, className: "h-5" },
    { axis: "vertical", size: 6, className: "h-6" },
    { axis: "vertical", size: 8, className: "h-8" },
    { axis: "vertical", size: 10, className: "h-10" },
    { axis: "vertical", size: 12, className: "h-12" },
    { axis: "vertical", size: 16, className: "h-16" },
    { axis: "vertical", size: 20, className: "h-20" },
    { axis: "vertical", size: 24, className: "h-24" },
  ],
  defaultVariants: {
    axis: "vertical",
    size: 4,
  },
});
