name: Deploy

on:
  workflow_call:
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0

  preview:
    name: 🤓 Preview deployment
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [cancel]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📡 Setup
        uses: ./.github/setup

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  deploy:
    name: 🚀 Deploy
    needs: [cancel]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📡 Setup
        uses: ./.github/setup

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project artifacts to vercel
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}

