name: Deploy

on:
  workflow_call:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}

jobs:
  preview:
    name: 🤓 Preview deployment
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📡 Setup
        uses: ./.github/setup

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=preview --token="$VERCEL_ACCESS_TOKEN"

      - name: Build project artifacts
        run: vercel build --token="$VERCEL_ACCESS_TOKEN"

      - name: Deploy project artifacts to vercel
        run: vercel deploy --prebuilt --token="$VERCEL_ACCESS_TOKEN"

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 📡 Setup
        uses: ./.github/setup

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production --token="$VERCEL_ACCESS_TOKEN"

      - name: Build project artifacts
        run: vercel build --token="$VERCEL_ACCESS_TOKEN"

      - name: Deploy project artifacts to vercel
        run: vercel deploy --token="$VERCEL_ACCESS_TOKEN"

